version: '3'
services:
  bgp:
    image: ztos-bgp
    networks:
      - ztos-network

  wireguard:
    image: ztos-wireguard
    networks:
      - ztos-network
    cap_add:
      - NET_ADMIN

  macsec:
    image: ztos-macsec
    networks:
      - ztos-network
    cap_add:
      - NET_ADMIN

  gpu-offload:
    image: ztos-gpu-offload
    networks:
      - ztos-network
    gpus: all

  api:
    image: ztos-api
    networks:
      - ztos-network
    ports:
      - "3000:3000"

  web:
    image: ztos-web
    networks:
      - ztos-network
    ports:
      - "8080:80"

  cli:
    image: ztos-cli
    networks:
      - ztos-network
    cap_add:
      - NET_ADMIN

networks:
  ztos-network:
    driver: bridge
